services:
  db:
    image: pgvector/pgvector:pg18-trixie
    container_name: chat-memory-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_memory
    ports:
      - "3245:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: